name: forestring_stu
description: "실제 운영 중인 포레스트링 학생·보호자용 수업 일정 관리 앱."
publish_to: 'none'
version: 3.0.2+14

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  table_calendar: ^3.1.2
  intl: any
  provider: ^6.0.5
  shared_preferences: ^2.3.2
  supabase_flutter: ^2.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/img/student_app_icon.png
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/img/
  fonts:
    - family: ELAND
      fonts:
        - asset: assets\\fonts\\ELAND_초이스OTF-B.otf
          weight: 700
        - asset: assets\\fonts\\ELAND_초이스OTF-L.otf
          weight: 300
        - asset: assets\\fonts\\ELAND_초이스OTF-M.otf
          weight: 500
    - family: OpenSans
      fonts:
        - asset: assets\\fonts\\OpenSans-Bold.ttf
          weight: 700
        - asset: assets\\fonts\\OpenSans-Light.ttf
          weight: 300
        - asset: assets\\fonts\\OpenSans-Medium.ttf
          weight: 500
