// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt5UdWJuxsKSC5Jo74TpFhNC-6f9dzd94',
    appId: '1:979880986063:web:f432e7683dcfcc4fefbeba',
    messagingSenderId: '979880986063',
    projectId: 'forestring-student',
    authDomain: 'forestring-student.firebaseapp.com',
    storageBucket: 'forestring-student.appspot.com',
    measurementId: 'G-579YFF60RB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSt3aljAj9rrCUREWto8GxRITw88zbqSc',
    appId: '1:979880986063:android:4601e4d0992fd098efbeba',
    messagingSenderId: '979880986063',
    projectId: 'forestring-student',
    storageBucket: 'forestring-student.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACO2zd08LXpDCG2RPXEcn-wrMwkOK1qnI',
    appId: '1:979880986063:ios:6b981494d7af4a56efbeba',
    messagingSenderId: '979880986063',
    projectId: 'forestring-student',
    storageBucket: 'forestring-student.appspot.com',
    iosBundleId: 'com.example.forestringStu',
  );
}
